### ISSUE TITLE
Feature request: Manual Mapping

### ISSUE THREAD

**Issue by Frazzer951** [Taxel/PlexTraktSync#1000]
### Feature description
For many Anime shows the script has trouble matching the correct episodes from plex to what they are in Trakt. A possible fix for this would allow for manual mapping of shows from plex to trakt.

### Use case

As stated above it would fix the issue of the sync script failing to match shows to their proper ids in trakt.

### Workarounds

None that I know of

### Plan to implement

I would be willing to help implement this if a consensus on how it should be done/implemented can be decided upon. 
A good example would be how `PlexAniSync` handles custom mapping defined at https://github.com/RickDB/PlexAniSync#custom-anime-mapping

**Comment by twolaw** [comment]
Could you give detailed examples of those matching troubles ?

**Comment by twolaw** [comment]
> A possible fix for this would allow for manual mapping of shows from plex to trakt.

Not efficient because only local. Why not collaborate by updating the show datasource so that everyone benefits from it ?

For any matching problem in Plex, you need to follow those rules :
- https://support.plex.tv/articles/migrating-a-tv-library-to-use-the-new-plex-tv-series-agent-scanner/
- https://support.plex.tv/articles/201018497-fix-match-match/
- https://support.plex.tv/articles/plexmatch/

For a matching problem in Trakt, just edit the show page on the source (often [tmdb](https://www.themoviedb.org/)). Trakt rules :
- https://support.trakt.tv/support/solutions/articles/70000260936-how-does-movie-tv-show-information-metadata-get-updated-how-can-i-refresh-or-sync-trakt-to-tmdb-
- https://support.trakt.tv/support/solutions/articles/70000264977
