### ISSUE TITLE
Inconsistency with config locations

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#45]
It's very confusing that configuration is spewed around in multiple places:
- config.json
- .env
- .pytrakt.json

and config.json is even committed to git, so must be careful when pushing changes.

**Comment by glensc** [comment]
what would be the preferred way to store config?

I'm willing to look into that moving all config to a single place.

**Comment by twolaw** [comment]
Good idea.
config.json would be the best place I think.

**Comment by glensc** [comment]
but config.json is git-committed, and we need to store secrets, should we use config.json from project as template? or use xdg paths instead ($XDG_CONFIG_HOME:-$HOME/.config), i.e store in user home?

**Comment by twolaw** [comment]
Previously .env and .pytrack.json were in home folder.
I moved them to script folder to allow multiple instances of the script for the same user on same machine.

Maybe 2 files would be a good solution : `config.json` and `secrets.json` (or whatever the name).
This solution avoids access error when user still have config.json opened and script try to write token to file.

**Comment by twolaw** [comment]
`.pytrakt.json` is written by pytrakt module so it is impossible to write anything else in it, it would be erased.
Maybe renaming `.env` to something more significant would be a good move.

And also moving base_url from `config.json` to `.env` because script can find it without user and it allows sync with friend's Plex server (#44).
