### ISSUE TITLE
TypeError: '<' not supported between instances of 'Movie' and 'Movie'

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#74]
```
Processing section TV Shows
Traceback (most recent call last):
  File "/home/glen/scm/mediaserver/plex/Plugins/PlexTraktSync/main.py", line 354, in <module>
    main()
  File "/home/glen/scm/mediaserver/plex/Plugins/PlexTraktSync/main.py", line 345, in main
    listutil.updatePlexLists(plex)
  File "/home/glen/scm/mediaserver/plex/Plugins/PlexTraktSync/trakt_list_util.py", line 61, in updatePlexLists
    l.updatePlexList(plex)
  File "/home/glen/scm/mediaserver/plex/Plugins/PlexTraktSync/trakt_list_util.py", line 36, in updatePlexList
    _, plex_movies_sorted = zip(*sorted(self.plex_movies))
TypeError: '<' not supported between instances of 'Movie' and 'Movie'
```

**Comment by glensc** [comment]
The error went away after a retry (because requests cached?), but worth researching what happened.

**Comment by twolaw** [comment]
Maybe you have the same movie in differents libraries.
I know how to fix this.

**Comment by glensc** [comment]
Yes, very likely, I have "Movies" and "Movies (Archive)" libraries, so I do move the files around.

**Comment by twolaw** [comment]
I wonder what is the expected behavior in such situation.

Example : in your trakt watchlist at rank 2 you have **The Mask** movie.
And you have **The Mask** in 720p in Plex library `Kids`, **The Mask** 1080p in library `Movies` and The Mask 3D in library `3D Movies`. All are the same movie from 1994 so have the same id.

If you sync all those libraries, which version of the movie do you expect to be added in the Plex playlist "Trakt watchlist" ?

I would say the first found, so if libraries are sync alphabetically, it would be the 3D version. 😄 
If you add the 3 versions, it would mess up the list and ranks.
