### ISSUE TITLE
Not everything is syncing from one of my managed users to trakt.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Taxel/PlexTraktSync#97]
It's only syncing TV shows from the looks of it and it doesn't even pickup all the watched episodes. There doesn't seem to be any errors.

**Comment by JpF4E** [comment]
The movies is probably because of this #56. There's a branch with this fixed: #86.
The TV shows could be related to this: #95. If you run the script again does it sync some more episodes?

This project deserved a development branch where the PRs are included... they seem to work even though some of them are poorly coded...

**Comment by Cookie-Monster-Coder** [comment]
Thanks for the fast response! It does seem to add more episodes everytime I run the script. So it does seem to be rate-limiting as mentioned.

I'll try both the new branches later tonight and report back.

**Comment by JpF4E** [comment]
@glensc / @Taxel how about merging these PRs into one "develop" branch so we update the script with the new features without worrying about new functionality?
